// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Mt3paxW_GWabP5u4bXeMbKJDmgds2dM',
    appId: '1:740472060904:web:2dd9c8a5b61bb0f358425d',
    messagingSenderId: '740472060904',
    projectId: 'padika-5acd4',
    authDomain: 'padika-5acd4.firebaseapp.com',
    storageBucket: 'padika-5acd4.appspot.com',
    measurementId: 'G-XJ1P376SN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcq19bXdHfFeGSiNUOExuGxBqBZyexo4E',
    appId: '1:740472060904:android:6c0c37c5c1d9129b58425d',
    messagingSenderId: '740472060904',
    projectId: 'padika-5acd4',
    storageBucket: 'padika-5acd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnBlf-yMgoHDMNixqjx86VRzoqC6sXpR8',
    appId: '1:740472060904:ios:2c143435f389a50b58425d',
    messagingSenderId: '740472060904',
    projectId: 'padika-5acd4',
    storageBucket: 'padika-5acd4.appspot.com',
    iosBundleId: 'com.example.padika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnBlf-yMgoHDMNixqjx86VRzoqC6sXpR8',
    appId: '1:740472060904:ios:b0ace931a4ce12ad58425d',
    messagingSenderId: '740472060904',
    projectId: 'padika-5acd4',
    storageBucket: 'padika-5acd4.appspot.com',
    iosBundleId: 'com.example.padika.RunnerTests',
  );
}
